const FACTORY='0x7eD598BcEf8bd9Edd8C97A195C6d13f40801EC7e';
const CLASSIC_FACTORIES=['0xA5aAb3F0c6EeadF30Ef1D3Eb997108E976351feB','0x0c37a24F5D23A486FA692d1500881d698B1F77a4'];
const TOPIC_CLASSIC_LAUNCH='0xdb51ea9ad51ab453a65a4cb7e60c3cb378c9501bb002609f8f97778fb6c4235a';
const TOPIC_CLASSIC_SWAP='0xc42079f94a6350d7e6235f29174924f928cc2ac818eb64fed8004e115fbcca67';
const TOPIC_LAUNCH='0x8d4aad4953d0ca700d468f3753aa14432d1b35b43ec6409f051fb6aa43a89607';
const TOPIC_BUY='0xec36bf571f136799e8dc0b0b8bea4b04d8bd3d43de838aab0d5fc21d4cbfc455';
const TOPIC_SELL='0x8113d738abdcb6b38357e9d53a54a7157861a09031b453651f0fe7fe151f59df';
const ZERO='0x0000000000000000000000000000000000000000';
const unhex=h=>BigInt(h||'0x0');
const signed=h=>{const v=unhex(h),M=1n<<256n,H=1n<<255n;return v>=H?v-M:v};
const hex=n=>'0x'+BigInt(n).toString(16);
const word=(data,i)=>'0x'+String(data||'0x').slice(2+i*64,2+(i+1)*64);
const topicAddr=t=>'0x'+String(t).slice(-40);
const dataAddr=(d,i)=>'0x'+word(d,i).slice(-40);
const lower=a=>String(a||'').toLowerCase();
const abs=x=>x<0n?-x:x;
const fmt18Big=n=>{n=abs(BigInt(n));const whole=n/10n**18n,frac=(n%10n**18n).toString().padStart(18,'0').slice(0,6).replace(/0+$/,'');return frac?`${whole}.${frac}`:`${whole}`};
const fmt18=v=>fmt18Big(unhex(v));
function decodeString(hexdata){try{let h=String(hexdata||'0x').slice(2);if(!h)return'';const offset=Number(BigInt('0x'+h.slice(0,64)));const len=Number(BigInt('0x'+h.slice(offset*2,offset*2+64)));const body=h.slice(offset*2+64,offset*2+64+len*2);return Buffer.from(body,'hex').toString('utf8').replace(/\0/g,'')}catch{return''}}

export class RobinhoodProvider{
  constructor({rpcUrl,rpcFallback,initialLookback=24000}){
    this.urls=[rpcUrl,rpcFallback].filter(Boolean);this.urlIndex=0;this.initialLookback=BigInt(initialLookback);
    this.lastBlock=null;this.curves=new Map;this.classic=new Map;this.classicPools=new Map;this.tokens=new Map;this.events=[];this.head=0n;this.id=1;this.blockTimes=new Map;
  }
  async rpc(method,params=[]){let last;for(let i=0;i<this.urls.length;i++){const url=this.urls[(this.urlIndex+i)%this.urls.length];try{const r=await fetch(url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',id:this.id++,method,params}),signal:AbortSignal.timeout(12000)});if(!r.ok)throw new Error(`HTTP ${r.status}`);const d=await r.json();if(d.error)throw new Error(d.error.message||'rpc error');this.urlIndex=(this.urlIndex+i)%this.urls.length;return d.result}catch(e){last=e}}throw last||new Error('rpc unavailable')}
  async init(seed={}){for(const l of seed.launches||[])if(l?.token){if(l.protocol==='PONS CLASSIC'&&l.pool){this.classic.set(lower(l.token),l);this.classicPools.set(lower(l.pool),l)}else if(l.curve)this.curves.set(lower(l.curve),l);this.tokens.set(lower(l.token),l)}if(seed.lastChainBlock)this.lastBlock=BigInt(seed.lastChainBlock);return this.poll(true)}
  async ethCall(to,data){return this.rpc('eth_call',[{to,data},'latest'])}
  async tokenMeta(token){const prev=this.tokens.get(lower(token));if(prev?.symbol&&prev?.name)return prev;const [sr,nr,dr]=await Promise.allSettled([this.ethCall(token,'0x95d89b41'),this.ethCall(token,'0x06fdde03'),this.ethCall(token,'0x313ce567')]);return{symbol:sr.status==='fulfilled'?decodeString(sr.value)||'TOKEN':'TOKEN',name:nr.status==='fulfilled'?decodeString(nr.value)||'Robinhood token':'Robinhood token',decimals:dr.status==='fulfilled'?Number(unhex(dr.value)):18}}
  async blockTime(blockNumber){const k=String(blockNumber);if(this.blockTimes.has(k))return this.blockTimes.get(k);let iso=new Date().toISOString();try{const b=await this.rpc('eth_getBlockByNumber',[blockNumber,false]);if(b?.timestamp)iso=new Date(Number(unhex(b.timestamp))*1000).toISOString()}catch{}this.blockTimes.set(k,iso);if(this.blockTimes.size>1200)this.blockTimes.delete(this.blockTimes.keys().next().value);return iso}
  async logs(address,topics,from,to){return this.rpc('eth_getLogs',[{address,topics,fromBlock:hex(from),toBlock:hex(to)}])}
  async poll(initial=false){this.head=unhex(await this.rpc('eth_blockNumber'));let from=this.lastBlock!=null?this.lastBlock+1n:this.head-(initial?this.initialLookback:1200n);if(from<0n)from=0n;if(from>this.head)return this.snapshot();for(let s=from;s<=this.head;s+=1200n){const e=s+1199n>this.head?this.head:s+1199n;await this.scanLaunches(s,e);await this.scanClassicLaunches(s,e);await this.scanTrades(s,e);await this.scanClassicTrades(s,e)}this.lastBlock=this.head;return this.snapshot()}
  async scanLaunches(from,to){let logs=[];try{logs=await this.logs(FACTORY,[TOPIC_LAUNCH],from,to)}catch{return}for(const l of logs){if(!l.topics?.[1]||!l.topics?.[2])continue;const token=topicAddr(l.topics[1]),curve=topicAddr(l.topics[2]),deployer=topicAddr(l.topics[3]),pairToken=dataAddr(l.data,0);const meta=await this.tokenMeta(token);const createdAt=await this.blockTime(l.blockNumber);const item={token,curve,deployer,pairToken,protocol:'PONS V2',launchConfigId:Number(unhex(word(l.data,1))),graduationThreshold:String(unhex(word(l.data,2))),blockNumber:String(unhex(l.blockNumber)),createdAt,symbol:meta.symbol,name:meta.name,decimals:meta.decimals};this.curves.set(lower(curve),item);this.tokens.set(lower(token),item)}}
  async scanClassicLaunches(from,to){for(const factory of CLASSIC_FACTORIES){let logs=[];try{logs=await this.logs(factory,[TOPIC_CLASSIC_LAUNCH],from,to)}catch{continue}for(const l of logs){if(!l.topics?.[1])continue;const token=topicAddr(l.topics[1]),deployer=topicAddr(l.topics[2]),pairToken=dataAddr(l.data,0),pool=dataAddr(l.data,1);const meta=await this.tokenMeta(token);const createdAt=await this.blockTime(l.blockNumber);const item={token,pool,curve:pool,deployer,pairToken,blockNumber:String(unhex(l.blockNumber)),createdAt,symbol:meta.symbol,name:meta.name,decimals:meta.decimals,protocol:'PONS CLASSIC',dexId:Number(unhex(word(l.data,2))),launchConfigId:Number(unhex(word(l.data,3)))};this.classic.set(lower(token),item);this.classicPools.set(lower(pool),item);this.tokens.set(lower(token),item)}}}
  async scanTrades(from,to){const curves=[...this.curves.values()].map(x=>x.curve);for(let i=0;i<curves.length;i+=70){const batch=curves.slice(i,i+70);let logs=[];try{logs=await this.logs(batch,[[TOPIC_BUY,TOPIC_SELL]],from,to)}catch{continue}for(const l of logs){const launch=this.curves.get(lower(l.address));if(!launch)continue;const isBuy=lower(l.topics[0])===TOPIC_BUY;const id=`${l.transactionHash}:${l.logIndex}`;if(this.events.some(x=>x.id===id))continue;const e={id,txHash:l.transactionHash,blockNumber:String(unhex(l.blockNumber)),side:isBuy?'BUY':'SELL',wallet:topicAddr(l.topics[1]),recipient:topicAddr(l.topics[2]),token:launch.token,curve:launch.curve,symbol:launch.symbol,name:launch.name,quoteAmount:fmt18(isBuy?word(l.data,0):word(l.data,1)),quoteSymbol:lower(launch.pairToken)===ZERO?'ETH':'QUOTE',fee:String(unhex(word(l.data,2))),tax:String(unhex(word(l.data,3))),createdAt:await this.blockTime(l.blockNumber),source:'PONS V2'};this.events.unshift(e)}}this.events=this.events.slice(0,800)}
  async scanClassicTrades(from,to){const pools=[...this.classicPools.keys()];for(let i=0;i<pools.length;i+=70){const batch=pools.slice(i,i+70);let logs=[];try{logs=await this.logs(batch,[TOPIC_CLASSIC_SWAP],from,to)}catch{continue}for(const l of logs){const launch=this.classicPools.get(lower(l.address));if(!launch)continue;const id=`${l.transactionHash}:${l.logIndex}`;if(this.events.some(x=>x.id===id))continue;const amount0=signed(word(l.data,0)),amount1=signed(word(l.data,1));const tokenIs0=BigInt(lower(launch.token))<BigInt(lower(launch.pairToken));const tokenAmount=tokenIs0?amount0:amount1,quoteAmount=tokenIs0?amount1:amount0;const isBuy=tokenAmount<0n;const sender=l.topics?.[1]?topicAddr(l.topics[1]):null,recipient=l.topics?.[2]?topicAddr(l.topics[2]):null;this.events.unshift({id,txHash:l.transactionHash,blockNumber:String(unhex(l.blockNumber)),side:isBuy?'BUY':'SELL',wallet:recipient||sender,recipient,sender,token:launch.token,curve:launch.pool,symbol:launch.symbol,name:launch.name,quoteAmount:fmt18Big(quoteAmount),quoteSymbol:'ETH',fee:null,tax:null,createdAt:await this.blockTime(l.blockNumber),source:'PONS CLASSIC'})}}this.events=this.events.slice(0,800)}
  snapshot(){const launches=[...this.classic.values(),...this.curves.values()].sort((a,b)=>Number(a.blockNumber)-Number(b.blockNumber)).slice(-600);return{head:String(this.head),lastChainBlock:String(this.lastBlock||0n),launches,trades:this.events.slice(0,600),factory:FACTORY,classicFactories:CLASSIC_FACTORIES}}
}
