import {A,c,lime,danger,amber,muted,soft,pad,trunc,hr,visibleLength} from './ansi.mjs';
import {logoLines,baraLines,miniBara} from './logo.mjs';
import {compact,usd,pct,short,age,verdict,score,pnl,links} from './format.mjs';
const box=(title,w,lines=[])=>{const out=[soft('┌'+` ${title} `.padEnd(w-1,'─')+'┐')];for(const l of lines){const t=trunc(l,w-4);out.push(soft('│ ') + pad(t,w-4)+soft(' │'))}out.push(soft('└'+''.padEnd(w-2,'─')+'┘'));return out};
function ruleLine(k,v){return `${soft(k.padEnd(18))} ${c(A.white,String(v))}`}
function row(cand,w,selected=false){const t=cand.token,tr=cand.trader;const name=tr?.name||tr?.handle||'market scout';const v=cand.verdict==='FIRE'?'FIRE':'SKIP';const why=cand.reasons[0]||'all walls passed';const base=`${verdict(v)} ${c(A.bold,'$'+String(t.symbol||'?').padEnd(10).slice(0,10))} ${score(t.score)} ${trunc(name,16).padEnd(16)} ${String(t.change24h>=0?pct(t.change24h):pct(t.change24h)).padStart(8)}  ${trunc(why,Math.max(8,w-68))}`;return(selected?c(A.bgGray,base):base)}
export function renderTui(rt,state){
  const W=Math.max(100,process.stdout.columns||140),H=Math.max(30,process.stdout.rows||42);const left=Math.max(62,Math.floor(W*.58)),right=W-left-1;const lines=[];const logo=logoLines();
  const st=rt.status(),rules=st.rules;for(let i=0;i<6;i++){const rhs=i===0?`${miniBara()}   ${lime('COPYTRADE TERMINAL')}   ${muted('Robinhood Chain')}`:i===1?`${soft('source')} ${st.mode==='LIVE'?c(A.brightGreen,'LIVE'):amber(st.mode)}  ${soft('fomo')} ${st.providers.fomo}  ${soft('dex')} ${st.providers.dex}  ${soft('rpc')} ${st.providers.rpc}`:i===2?`${soft('hunters')} ${c(A.white,st.hunters)}  ${soft('tokens')} ${c(A.white,st.tokens)}  ${soft('paper')} ${c(A.white,st.positions)}  ${soft('budget')} ${c(A.white,`${Number(st.spentEth).toFixed(3)}/${rules.sessionBudgetEth.toFixed(3)} ETH`)}`:i===3?`${soft('walls')} score≥${rules.minScore} · mcap≤$${Math.round(rules.maxMarketCap/1e6)}M · liq≥$${Math.round(rules.minLiquidity/1e3)}K · max ${rules.maxPositions} pos`:i===4?`${soft('exits')} TP +${rules.takeProfitPct}% · SL ${rules.stopLossPct}% · trail ${rules.trailingPct}% · ${rules.maxHoldMin}m clock`:state.engine?c(A.brightGreen,'ENGINE RUNNING  ') + muted('space paper-copy · c track · ↑↓ select'):muted('ENGINE PAUSED   p start · q quit · r sync');lines.push(pad(logo[i]||'',left-1)+soft('│')+trunc(rhs,right-1))}
  lines.push(soft(hr(left-1))+soft('┼')+soft(hr(right)));
  const candidates=rt.candidates||[];const filtered=candidates.filter(x=>state.filter==='fire'?x.verdict==='FIRE':state.filter==='skip'?x.verdict==='SKIP':true);if(state.selected>=filtered.length)state.selected=Math.max(0,filtered.length-1);const sel=filtered[state.selected]||candidates[0];
  const leftRows=[];leftRows.push(`${soft(' newest first ')} ${state.filter==='all'?lime('ALL'):state.filter==='fire'?c(A.brightGreen,'FIRE'):danger('SKIP')}  ${soft('p start/stop · f filter · / search · space paper')}`);const maxFeed=Math.max(10,H-17);const start=Math.max(0,state.selected-Math.floor(maxFeed/2));for(let i=start;i<Math.min(filtered.length,start+maxFeed);i++)leftRows.push(row(filtered[i],left-2,i===state.selected));while(leftRows.length<maxFeed+1)leftRows.push('');
  const detail=[];if(sel){const t=sel.token,tr=sel.trader;detail.push(lime(`$${t.symbol||'?'}  COPY SCORE ${t.score}`));detail.push(`${c(A.bold,tr?.name||tr?.handle||'NO CONFIRMED TRADER')} ${tr?.handle?muted('@'+tr.handle):''}`);detail.push(`${soft('verdict')} ${verdict(sel.verdict)}  ${soft('source')} ${sel.kind.toUpperCase()}`);detail.push('');detail.push(`${soft('market cap')} ${usd(t.marketCap)}   ${soft('liq')} ${usd(t.liquidity)}`);detail.push(`${soft('24h vol')}  ${usd(t.volume24h)}   ${soft('24h')} ${Number(t.change24h)>=0?c(A.brightGreen,pct(t.change24h)):danger(pct(t.change24h))}`);detail.push(`${soft('contract')} ${short(t.address)}`);if(sel.pnl!=null)detail.push(`${soft('trader pnl')} ${pnl(sel.pnl)}`);detail.push('');detail.push(sel.reasons.length?danger('REFUSED BY')+': '+sel.reasons.join(' · '):c(A.brightGreen,'ALL COPY WALLS PASSED'));detail.push('');detail.push(`${soft('open')} ${links(t.address)}`);detail.push('');detail.push(soft('COPYBARA READ'));for(const x of baraLines().slice(0,5))detail.push(x);}
  const infoBox=box('selected read',right-1,detail).slice(0,maxFeed+1);for(let i=0;i<maxFeed+1;i++)lines.push(pad(leftRows[i]||'',left-1)+soft('│')+(infoBox[i]||''));
  lines.push(soft(hr(left-1))+soft('┼')+soft(hr(right)));
  const pos=rt.store.positions||[];const posText=pos.length?pos.slice(0,3).map(p=>`${c(A.brightGreen,'PAPER')} $${p.symbol} ${pct(p.pnlPct)} ${age(p.openedAt)}`).join(' · '):muted('no paper positions');const help=`${soft('positions')} ${posText}`;const cmd=`${soft('keys')} p engine · f filter · ↑↓ select · space paper · c track · r refresh · q quit`;lines.push(pad(trunc(help,left-1),left-1)+soft('│')+trunc(cmd,right-1));
  return lines.slice(0,H).map(x=>trunc(x,W)).join('\n')
}
export function lineEvent(cand){const t=cand.token,tr=cand.trader;const time=new Date().toTimeString().slice(0,8);const name=tr?.name||tr?.handle||'market';const why=cand.reasons[0]||'all walls passed';return `${soft(time)} ${verdict(cand.verdict)} ${c(A.bold,'$'+String(t.symbol||'?').padEnd(11).slice(0,11))} score ${score(t.score)}  ${trunc(name,18).padEnd(18)}  mcap ${usd(t.marketCap).padEnd(9)} liq ${usd(t.liquidity).padEnd(8)}  ${why}`}
export function header(rt,mode='hunt'){const st=rt.status(),r=st.rules;return [...logoLines(),'',`${lime('copy')} ${mode} · ${st.mode.toLowerCase()} · ${r.buySizeEth.toFixed(2)} ETH per copy · budget ${r.sessionBudgetEth.toFixed(2)} ETH · max open ${r.maxPositions} · min score ${r.minScore}`,`${soft('sources')} fomo ${st.providers.fomo} · dex ${st.providers.dex} · rpc ${st.providers.rpc}`,soft('open token links are OSC-8 clickable in Windows Terminal, iTerm2, kitty and VS Code'),soft(hr(Math.min(150,process.stdout.columns||120)))].join('\n')}
